import { spawnSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const workspaceRoot = resolve(import.meta.dirname, "../../..");
const drizzleDir = join(workspaceRoot, "packages/core/drizzle");
const outPath = join(workspaceRoot, "packages/core/drizzle/embedded-migrations.ts");

const journal = JSON.parse(readFileSync(join(drizzleDir, "meta/_journal.json"), "utf-8"));

const sqlFiles: Record<string, string> = {};
for (const entry of journal.entries) {
  const sqlPath = join(drizzleDir, `${entry.tag}.sql`);
  sqlFiles[entry.tag] = readFileSync(sqlPath, "utf-8");
}

const journalStr = JSON.stringify(journal, null, 2).replace(/"(\w+)":/g, "$1:");

const migrationsStr = Object.entries(sqlFiles)
  .map(([k, v]) => `  "${k}":\n    ${JSON.stringify(v)}`)
  .join(",\n");

const output = `// AUTO-GENERATED by apps/cli/scripts/embed-migrations.ts — do not edit manually

export const journal = ${journalStr} as const;

export const migrations: Record<string, string> = {
${migrationsStr}
} as const;
`;

writeFileSync(outPath, output);

spawnSync("bunx", ["biome", "format", "--write", outPath], {
  stdio: "inherit",
  cwd: workspaceRoot,
});

console.log(`Embedded ${Object.keys(sqlFiles).length} migration files into embedded-migrations.ts`);
